---
# From https://github.com/mohankumargupta/raspberrypi-ansible/blob/master/raspbian-setup.yml
# And https://raspberrypi.stackexchange.com/questions/28907/how-could-one-automate-the-raspbian-raspi-config-setup
# And https://github.com/giuaig/ansible-raspi-config/blob/master/raspi-config.yml

# I2C
- name: Get I2C status
  shell: "raspi-config nonint get_i2c"
  register: i2c_status
  changed_when: False

- name: Print I2C status
  debug:
    msg: "I2C status is: {{ i2c_status.stdout }}"

- name: Enable I2C
  shell: "raspi-config nonint do_i2c 0"
  register: i2c_output
  when: (rack_pi_enable_i2c | bool) and i2c_status.stdout != '0'

- name: Print I2C output
  debug:
    msg: "I2C output: {{ i2c_output.stdout }}"

# SPI
- name: Get SPI status
  shell: "raspi-config nonint get_spi"
  register: spi_status
  changed_when: False

- name: Print SPI status
  debug:
    msg: "SPI status is: {{ spi_status.stdout }}"

- name: Enable SPI
  shell: "raspi-config nonint do_spi 0"
  when: (rack_pi_enable_spi | bool) and spi_status.stdout != '0'

# Dependencies
- name: RackPi | Install dependencies
  apt:
    name: [ 'python3-pip', 'python3-pil', 'python-smbus', 'i2c-tools' ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

# for Python 3.3 specifically, using the 'pip3.3' executable
- name: Install pip dependencies
  pip:
    name: [ 'adafruit-circuitpython-ssd1306', 'psutil' ]
    executable: pip3

- name: Create install folder if needed
  file:
    path: "{{ rack_pi_script_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: RackPi | Deploy infoscreen script
  copy:
    src: home/rackpi/infoscreen.py
    dest: "{{ rack_pi_script_directory }}/infoscreen.py"
    mode: 0755

- name: Run script at startup
  blockinfile:
    path: /etc/rc.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK: infoscreen script for rack pi"
    insertbefore: exit 0
    block: |
      sudo python3 {{ rack_pi_script_directory }}/infoscreen.py &
