---

# Dependencies
- name: RackPi | Install dependencies
  apt:
    name: [ 'python3-pip', 'python3-pil', 'python-smbus', 'i2c-tools' ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

# for Python 3.3 specifically, using the 'pip3.3' executable
- name: Install pip dependencies
  pip:
    name: [ 'adafruit-circuitpython-ssd1306', 'psutil' ]
    executable: pip3

- name: Create install folder if needed
  file:
    path: "{{ rack_pi_script_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: RackPi | Deploy infoscreen script
  copy:
    src: home/rackpi/infoscreen.py
    dest: "{{ rack_pi_script_directory }}/infoscreen.py"
    mode: 0755

- name: Run script at startup
  blockinfile:
    path: /etc/rc.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK: infoscreen script for rack pi"
    insertbefore: exit 0
    block: |
      sudo python3 {{ rack_pi_script_directory }}/infoscreen.py &
