---
# From https://github.com/mohankumargupta/raspberrypi-ansible/blob/master/raspbian-setup.yml
# And https://raspberrypi.stackexchange.com/questions/28907/how-could-one-automate-the-raspbian-raspi-config-setup
# And https://github.com/giuaig/ansible-raspi-config/blob/master/raspi-config.yml

# SPI
- name: Get SPI status
  shell: "raspi-config nonint get_spi"
  register: spi_status
  changed_when: False

- name: Print SPI status
  debug:
    msg: "SPI status is: {{ spi_status.stdout }}"

- name: Enable SPI
  shell: "raspi-config nonint do_spi 0"
  when: not (is_test | bool) and spi_status.stdout != '0'
