---
# From https://github.com/mohankumargupta/raspberrypi-ansible/blob/master/raspbian-setup.yml
# And https://raspberrypi.stackexchange.com/questions/28907/how-could-one-automate-the-raspbian-raspi-config-setup
# And https://github.com/giuaig/ansible-raspi-config/blob/master/raspi-config.yml

# I2C
- name: Get I2C status
  shell: "raspi-config nonint get_i2c"
  register: i2c_status
  changed_when: False

- name: Print I2C status
  debug:
    msg: "I2C status is: {{ i2c_status.stdout }}"

- name: Enable I2C
  shell: "raspi-config nonint do_i2c 0"
  when: not (is_test | bool) and i2c_status.stdout != '0'
